import { chromium, type BrowserContext, type Page } from 'playwright-core'
import { join } from 'path'
import { existsSync, mkdirSync } from 'fs'
import { logger } from '../../utils/logger'

const SIGN_TIMEOUT = 10_000

interface SignRequest {
  platform: string
  cookie: string
  data: string
}

interface SignResult {
  signature: string
}

/**
 * Local signature service using Playwright.
 *
 * For each platform, maintains a hidden browser context with the creator page loaded.
 * When a signature is requested, evaluates the platform's signature JS in the browser context.
 *
 * This replaces yixiaoer's external signature server (qianming.yixiaoer.cn).
 */
export class SignService {
  private contexts = new Map<string, BrowserContext>()
  private pages = new Map<string, Page>()
  private initializing = new Map<string, Promise<void>>()

  /**
   * Get the signature for a given request.
   * Uses the platform's own JS running in a browser context.
   */
  async getSignature(platform: string, cookie: string, data: string): Promise<string> {
    try {
      switch (platform) {
        case 'douyin':
          return await this.getDouyinSignature(cookie, data)
        case 'xiaohongshu':
          return await this.getXhsSignature(cookie, data)
        case 'kuaishou':
          return await this.getKuaishouSignature(cookie, data)
        default:
          logger.warn(`[sign] No signature implementation for platform: ${platform}`)
          return ''
      }
    } catch (err) {
      logger.error(`[sign] Failed to get signature for ${platform}:`, err)
      return ''
    }
  }

  /**
   * Douyin a_bogus signature generation.
   *
   * The a_bogus parameter is generated by Douyin's anti-bot JS.
   * We load the creator page in a headless browser and call the signature function.
   */
  private async getDouyinSignature(cookie: string, data: string): Promise<string> {
    const page = await this.getOrCreatePage('douyin', cookie, 'https://creator.douyin.com/creator-micro/home')

    try {
      // Extract msToken from cookie
      const msTokenMatch = cookie.match(/msToken=([^;]+)/)
      const msToken = msTokenMatch ? msTokenMatch[1] : ''

      // Call the signature function in the browser context
      // The Douyin creator page loads a signature module that exposes
      // the a_bogus generation function
      const signature = await page.evaluate(
        ({ msToken, body }) => {
          return new Promise<string>((resolve) => {
            // Try to find the signature function in the page context
            // Douyin's signature module is typically loaded as a global or
            // accessible through the page's JS context

            // Method 1: Check for __NEXT_DATA__ or similar global
            const win = window as Record<string, unknown>

            // Method 2: Use the page's own XMLHttpRequest to trigger signature generation
            // The signature is computed when an API call is made
            const xhr = new XMLHttpRequest()
            const testUrl = `https://creator.douyin.com/aweme/v1/creator/user/info/?msToken=${msToken}&a_bogus=`

            // Intercept the request to capture the generated signature
            const origOpen = xhr.open
            xhr.open = function (method: string, url: string | URL) {
              const urlStr = typeof url === 'string' ? url : url.toString()
              if (urlStr.includes('a_bogus=')) {
                const match = urlStr.match(/a_bogus=([^&]+)/)
                if (match) {
                  resolve(match[1])
                }
              }
              return origOpen.call(this, method, url)
            }

            xhr.open('GET', testUrl)
            xhr.setRequestHeader('Cookie', document.cookie)
            xhr.onerror = () => resolve('')
            xhr.onload = () => resolve('')
            xhr.send()

            // Timeout fallback
            setTimeout(() => resolve(''), 5000)
          })
        },
        { msToken, body: data }
      )

      return signature || ''
    } catch (err) {
      logger.error('[sign] Douyin signature generation failed:', err)
      // Reset the page on error so it gets recreated
      this.resetPage('douyin')
      return ''
    }
  }

  /**
   * Xiaohongshu X-s / X-t signature generation.
   */
  private async getXhsSignature(cookie: string, data: string): Promise<string> {
    const page = await this.getOrCreatePage('xiaohongshu', cookie, 'https://creator.xiaohongshu.com/publish/publish')

    try {
      const signature = await page.evaluate(
        ({ data }) => {
          return new Promise<string>((resolve) => {
            // XHS uses X-s and X-t headers for signature
            // These are generated by their anti-bot JS
            const win = window as Record<string, unknown>

            // Try to find XHS signature function
            if (typeof win._webmsxyw === 'function') {
              const result = win._webmsxyw(data)
              resolve(JSON.stringify(result))
            } else {
              // Fallback: make a test request and intercept headers
              resolve('')
            }

            setTimeout(() => resolve(''), 3000)
          })
        },
        { data }
      )

      return signature || ''
    } catch (err) {
      logger.error('[sign] XHS signature generation failed:', err)
      this.resetPage('xiaohongshu')
      return ''
    }
  }

  /**
   * Kuaishou signature generation.
   */
  private async getKuaishouSignature(cookie: string, data: string): Promise<string> {
    // Kuaishou uses a simpler signing mechanism
    // The API calls don't require complex signatures like Douyin
    return ''
  }

  /**
   * Get or create a browser context and page for a platform.
   */
  private async getOrCreatePage(platform: string, cookie: string, url: string): Promise<Page> {
    // Wait if already initializing
    const initPromise = this.initializing.get(platform)
    if (initPromise) {
      await initPromise
    }

    const existingPage = this.pages.get(platform)
    if (existingPage && !existingPage.isClosed()) {
      // Update cookies
      const context = existingPage.context()
      await context.clearCookies()
      const cookieArray = cookie.split('; ').map((c) => {
        const [name, ...valueParts] = c.split('=')
        return {
          name: name.trim(),
          value: valueParts.join('='),
          domain: `.douyin.com`,
          path: '/'
        }
      })
      await context.addCookies(cookieArray)
      return existingPage
    }

    // Create new context and page
    const initResolve: (() => void)[] = []
    const initPromiseNew = new Promise<void>((resolve) => {
      initResolve.push(resolve)
    })
    this.initializing.set(platform, initPromiseNew)

    try {
      const profileDir = join(this.getSignDataDir(), platform)
      if (!existsSync(profileDir)) {
        mkdirSync(profileDir, { recursive: true })
      }

      const context = await chromium.launchPersistentContext(profileDir, {
        headless: true,
        args: [
          '--disable-blink-features=AutomationControlled',
          '--no-sandbox',
          '--disable-dev-shm-usage',
          '--disable-gpu'
        ],
        viewport: { width: 1920, height: 1080 },
        locale: 'zh-CN',
        userAgent:
          'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
        bypassCSP: true
      })

      // Set cookies
      await context.clearCookies()
      const cookieArray = cookie.split('; ').map((c) => {
        const [name, ...valueParts] = c.split('=')
        const domain = platform === 'douyin' ? '.douyin.com' : '.xiaohongshu.com'
        return {
          name: name.trim(),
          value: valueParts.join('='),
          domain,
          path: '/'
        }
      })
      await context.addCookies(cookieArray)

      const page = await context.newPage()

      // Add stealth scripts
      await page.addInitScript(() => {
        Object.defineProperty(navigator, 'webdriver', {
          get: () => undefined,
          configurable: true
        })
        delete (navigator as Record<string, unknown>).__proto__.webdriver
      })

      logger.info(`[sign] Loading ${platform} creator page: ${url}`)
      await page.goto(url, { waitUntil: 'domcontentloaded', timeout: 30000 })

      // Wait for page JS to initialize
      await page.waitForTimeout(5000)

      this.contexts.set(platform, context)
      this.pages.set(platform, page)

      logger.info(`[sign] ${platform} signature context ready`)
      return page
    } finally {
      initResolve[0]?.()
      this.initializing.delete(platform)
    }
  }

  private resetPage(platform: string): void {
    const page = this.pages.get(platform)
    if (page && !page.isClosed()) {
      page.close().catch(() => {})
    }
    this.pages.delete(platform)
  }

  private getSignDataDir(): string {
    const { app } = require('electron')
    const dir = join(app.getPath('userData'), 'sign-profiles')
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true })
    }
    return dir
  }

  /**
   * Clean up all browser contexts.
   */
  async dispose(): Promise<void> {
    for (const [platform, page] of this.pages) {
      try {
        if (!page.isClosed()) await page.close()
      } catch (err) {
        logger.error(`[sign] Error closing ${platform} page:`, err)
      }
    }
    for (const [platform, context] of this.contexts) {
      try {
        await context.close()
      } catch (err) {
        logger.error(`[sign] Error closing ${platform} context:`, err)
      }
    }
    this.pages.clear()
    this.contexts.clear()
  }
}

// Singleton instance
let signServiceInstance: SignService | null = null

export function getSignService(): SignService {
  if (!signServiceInstance) {
    signServiceInstance = new SignService()
  }
  return signServiceInstance
}
